/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPartnerManager__factory } from "./IPartnerManager__factory";
export { PartnerManager__factory } from "./PartnerManager__factory";
