export const REQUEST_NEW_SUBDOMAIN = 'REQUEST_NEW_SUBDOMAIN';
export const RECEIVE_NEW_SUBDOMAIN = 'RECEIVE_NEW_SUBDOMAIN';
export const ERROR_NEW_SUBDOMAIN = 'ERROR_NEW_SUBDOMAIN';
export const ERROR_NEW_SUBDOMAIN_CLOSE = 'ERROR_NEW_SUBDOMAIN_CLOSE';

export const CLEAR_SUBDOMAIN_LIST = 'CLEAR_SUBDOMAIN_LIST';
export const ADD_SUBDOMAIN_TO_LIST = 'ADD_SUBDOMAIN_TO_LIST';
