/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPartnerManager } from "./IPartnerManager";
export type { PartnerManager } from "./PartnerManager";
