/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPartnerConfiguration__factory } from "./IPartnerConfiguration__factory";
export { PartnerConfiguration__factory } from "./PartnerConfiguration__factory";
