export const REQUEST_ENABLE = 'REQUEST_ENABLE';
export const RECEIVE_ENABLE = 'RECEIVE_ENABLE';
export const ERROR_ENABLE = 'ERROR_ENABLE';

export const DISPLAY_AUTH_MODAL = 'DISPLAY_AUTH_MODAL';

export const REQUEST_AUTH_DOMAIN = 'REQUEST_AUTH_DOMAIN';
export const RECEIVE_AUTH_DOMAIN = 'RECEIVE_AUTH_DOMAIN';
export const ERROR_AUTH_DOMAIN = 'ERROR_AUTH_DOMAIN';
