export const SET_VIEW = 'SET_VIEW';
export const REQUEST_TRANSFER_DOMAIN = 'REQUEST_TRANSFER_DOMAIN';
export const RECEIVE_TRANSFER_DOMAIN = 'RECEIVE_TRANSFER_DOMAIN';
export const ERROR_TRANSFER_DOMAIN = 'ERROR_TRANSFER_DOMAIN';
export const HANDLE_ERROR_CLOSE = 'HANDLE_ERROR_CLOSE';
export const HANDLE_SUCCESS_CLOSE = 'HANDLE_SUCCESS_CLOSE';
export const CHECKSUM_ERROR = 'CHECKSUM_ERROR';
