/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBaseRegistrar } from "./IBaseRegistrar";
export type { PartnerRegistrar } from "./PartnerRegistrar";
