export const REQUEST_RESOLVE_ADDRESS = 'REQUEST_RESOLVE_ADDRESS';
export const RECEIVE_RESOLVE_ADDRESS = 'RECEIVE_RESOLVE_ADDRESS';

export const REQUEST_DOMAIN_STATE = 'REQUEST_DOMAIN_STATE';
export const RECEIVE_DOMAIN_STATE = 'RECEIVE_DOMAIN_STATE';
