export const REQUEST_RESOLVER = 'REQUEST_RESOLVER';
export const RECEIVE_RESOLVER = 'RECEIVE_RESOLVER';

export const REQUEST_SET_RESOLVER = 'REQUEST_SET_RESOLVER';
export const WAITING_SET_RESOLVER = 'WAITING_SET_RESOLVER';
export const RECEIVE_SET_RESOLVER = 'RECEIVE_SET_RESOLVER';
export const ERROR_SET_RESOLVER = 'ERROR_SET_RESOLVER';

export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';

export const REQUEST_CONTENT = 'REQUEST_CONTENT';
export const RECEIVE_CONTENT = 'RECEIVE_CONTENT';
export const ERROR_CONTENT = 'ERROR_CONTENT';
export const REQUEST_SET_CONTENT = 'REQUEST_SET_CONTENT';
export const RECEIVE_SET_CONTENT = 'RECEIVE_SET_CONTENT';
export const ERROR_SET_CONTENT = 'ERROR_SET_CONTENT';
export const CLOSE_SET_CONTENT = 'CLOSE_SET_CONTENT';

// non-redux action types
export const MULTICHAIN_RESOLVER = 'MULTICHAIN_RESOLVER';
export const PUBLIC_RESOLVER = 'PUBLIC_RESOLVER';
export const STRING_RESOLVER = 'STRING_RESOLVER';
export const UNKNOWN_RESOLVER = 'UNKNOWN_RESOLVER';

export const CONTENT_BYTES = 'CONTENT_BYTES';
export const CONTENT_BYTES_BLANK = '0x0000000000000000000000000000000000000000000000000000000000000000';
