export const REQUEST_GET_ADDR = 'REQUEST_GET_RESOLUTION';
export const RECEIVE_GET_ADDR = 'RECEIVE_GET_RESOLUTION';
export const ERROR_GET_ADDR = 'ERROR_GET_ADDR';

export const REQUEST_GET_CONTENT = 'REQUEST_GET_CONTENT';
export const RECEIVE_GET_CONTENT = 'RECEIVE_GET_CONTENT';
export const ERROR_GET_CONTENT = 'ERROR_GET_CONTENT';
