// addr
export const REQUEST_GET_ADDR = 'REQUEST_GET_RESOLUTION';
export const RECEIVE_GET_ADDR = 'RECEIVE_GET_RESOLUTION';
export const ERROR_GET_ADDR = 'ERROR_GET_ADDR';
export const VIEW_EDIT_ADDR = 'VIEW_EDIT_ADDR';
export const REQUEST_SET_ADDR = 'REQUEST_SET_ADDR';
export const RECEIVE_SET_ADDR = 'RECEIVE_SET_ADDR';
export const ERROR_SET_ADDR = 'ERROR_SET_ADDR';

// content
export const REQUEST_GET_CONTENT = 'REQUEST_GET_CONTENT';
export const RECEIVE_GET_CONTENT = 'RECEIVE_GET_CONTENT';
export const ERROR_GET_CONTENT = 'ERROR_GET_CONTENT';
export const VIEW_EDIT_CONTENT = 'VIEW_EDIT_CONTENT';
export const REQUEST_SET_CONTENT = 'REQUEST_SET_CONTENT';
export const RECEIVE_SET_CONTENT = 'RECEIVE_SET_CONTENT';
export const ERROR_SET_CONTENT = 'ERROR_SET_CONTENT';
