/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC677 } from "./ERC677";
export type { IERC677 } from "./IERC677";
export type { IERC677TransferReceiver } from "./IERC677TransferReceiver";
