/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPartnerConfiguration } from "./IPartnerConfiguration";
export type { PartnerConfiguration } from "./PartnerConfiguration";
