/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC677TransferReceiver,
  IERC677TransferReceiverInterface,
} from "../../../../@rsksmart/erc677/contracts/IERC677TransferReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "tokenFallback",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC677TransferReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IERC677TransferReceiverInterface {
    return new utils.Interface(_abi) as IERC677TransferReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC677TransferReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC677TransferReceiver;
  }
}
