export const ADD_TRANSACTION_ERROR = 'ADD_TRANSACTION_ERROR';
export const REMOVE_TRANSACTION_ERROR = 'REMOVE_TRANSACTION_ERROR';

export const ADD_TRANSACTION_CONFIRMED = 'ADD_TRANSACTION_CONFIRMED';
export const TRANSACTION_MINED = 'TRANSACTION_MINED';
