export const ADMIN_DOMAIN = 'ADMIN_DOMAIN';

export const REQUEST_DOMAIN_OWNER = 'REQUEST_DOMAIN_OWNER';
export const RECEIVE_DOMAIN_OWNER = 'RECEIVE_DOMAIN_OWNER';

export const REQUEST_DOMAIN_RESOLVER = 'REQUEST_DOMAIN_RESOLVER';
export const RECEIVE_DOMAIN_RESOLVER = 'RECEIVE_DOMAIN_RESOLVER';

export const REQUEST_DOMAIN_TTL = 'REQUEST_DOMAIN_TTL';
export const RECEIVE_DOMAIN_TTL = 'RECEIVE_DOMAIN_TTL';

export const ADD_SUBDOMAIN = 'ADD_SUBDOMAIN';

export const RECEIVE_SUBDOMAIN_OWNER = 'RECEIVE_SUBDOMAIN_OWNER';
