// owner
export const REQUEST_DOMAIN_OWNER = 'REQUEST_DOMAIN_OWNER';
export const RECEIVE_DOMAIN_OWNER = 'RECEIVE_DOMAIN_OWNER';
export const VIEW_EDIT_OWNER = 'VIEW_EDIT_OWNER';
export const REQUEST_SET_OWNER = 'REQUEST_SET_OWNER';
export const RECEIVE_SET_OWNER = 'RECEIVE_SET_OWNER';
export const ERROR_SET_OWNER = 'ERROR_SET_OWNER';

// resolver
export const REQUEST_DOMAIN_RESOLVER = 'REQUEST_DOMAIN_RESOLVER';
export const RECEIVE_DOMAIN_RESOLVER = 'RECEIVE_DOMAIN_RESOLVER';

// ttl
export const REQUEST_DOMAIN_TTL = 'REQUEST_DOMAIN_TTL';
export const RECEIVE_DOMAIN_TTL = 'RECEIVE_DOMAIN_TTL';

// subdomains
export const ADD_SUBDOMAIN = 'ADD_SUBDOMAIN';
export const RECEIVE_SUBDOMAIN_OWNER = 'RECEIVE_SUBDOMAIN_OWNER';
