export const REQUEST_REGISTRAR_GET_COST = 'REQUEST_REGISTRAR_GET_COST';
export const RECEIVE_REGISTRAR_GET_COST = 'RECEIVE_REGISTRAR_GET_COST';
export const REQUEST_REGISTRAR_COMMIT = 'REQUEST_REGISTRAR_COMMIT';
export const RECEIVE_REGISTRAR_COMMIT = 'RECEIVE_REGISTRAR_COMMIT';
