/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./Access";
export type { access };
import type * as feeManager from "./FeeManager";
export type { feeManager };
import type * as partnerConfiguration from "./PartnerConfiguration";
export type { partnerConfiguration };
import type * as partnerManager from "./PartnerManager";
export type { partnerManager };
import type * as registrar from "./Registrar";
export type { registrar };
import type * as renewer from "./Renewer";
export type { renewer };
import type * as testUtils from "./test-utils";
export type { testUtils };
export type { NodeOwner } from "./NodeOwner";
export type { RIF } from "./RIF";
export type { RNS } from "./RNS";
