/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBaseRegistrar__factory } from "./IBaseRegistrar__factory";
export { PartnerRegistrar__factory } from "./PartnerRegistrar__factory";
