export const notificationTypes = {
  ERROR: 'ERROR',
  TX: 'TX'
};

export const txTypes = {
  START_AUCTION: 'START_AUCTION',
  BID_AUCTION: 'BID_AUCTION',
  UNSEAL_AUCTION: 'UNSEAL_AUCTION',
  FINALIZE_AUCTION: 'FINALIZE_AUCTION',

  SET_OWNER: 'SET_OWNER',
  SET_RESOLVER: 'SET_RESOLVER',
  SET_TTL: 'SET_TTL',

  SET_ADDR: 'SET_ADDR',
  SET_CONTENT: 'SET_CONTENT'
}

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const VIEW_NOTIFICATION = 'VIEW_NOTIFICATION';
export const TX_MINED = 'TX_MINED';
