export const REQUEST_RESOLVE = 'REQUEST_RESOLVE';
export const RECEIVE_RESOLVE = 'RECEIVE_RESOLVE';
export const ERROR_RESOLVE = 'ERROR_RESOLVE';
export const REQUEST_CHAIN_RESOLVE = 'REQUEST_CHAIN_RESOLVE';
export const RECEIVE_CHAIN_RESOLVE = 'RECEIVE_CHAIN_RESOLVE';
export const ERROR_CHAIN_RESOLVE = 'ERROR_CHAIN_RESOLVE';
